In [1]:
from __future__ import (absolute_import, division, print_function, unicode_literals)

import os

import numpy as np
import pandas as pd

from surprise import SVD
from surprise import Dataset
from surprise import Reader
from surprise.model_selection import cross_validate

## Data Load - Movie lens 1M data

In [2]:
# 데이터가 없으면 Y해서 데이터 로드
data = Dataset.load_builtin('ml-1m')
df = pd.DataFrame(data.raw_ratings, columns=["user", "item", "rate", "id"])

In [3]:
file_path = os.path.expanduser('~/.surprise_data/ml-1m/ml-1m/ratings.dat')
reader = Reader(line_format = 'user item rating timestamp', sep = '::')
data = Dataset.load_from_file(file_path, reader = reader)

In [4]:
algo = SVD()
cross_validate(algo, data, measures = ['RMSE', 'MAE'], cv = 5, verbose = True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.8718  0.8728  0.8723  0.8747  0.8762  0.8736  0.0017  
MAE (testset)     0.6839  0.6849  0.6853  0.6867  0.6883  0.6858  0.0015  
Fit time          57.85   59.03   60.90   70.65   56.04   60.89   5.13    
Test time         2.45    2.74    4.08    2.70    3.47    3.09    0.60    


{'test_rmse': array([0.87180998, 0.87277481, 0.87232613, 0.87472084, 0.87623166]),
 'test_mae': array([0.68391942, 0.68492126, 0.68533639, 0.68671832, 0.68826271]),
 'fit_time': (57.8542320728302,
  59.0256450176239,
  60.89537787437439,
  70.65435290336609,
  56.03543186187744),
 'test_time': (2.4530200958251953,
  2.7428760528564453,
  4.076212167739868,
  2.6992640495300293,
  3.4739699363708496)}

In [5]:
df = pd.DataFrame(data.raw_ratings, columns = ['uid', 'iid', 'rate', 'timestamp'])

In [6]:
df

uid   iid  rate  timestamp
0           1  1193   5.0  978300760
1           1   661   3.0  978302109
2           1   914   3.0  978301968
3           1  3408   4.0  978300275
4           1  2355   5.0  978824291
5           1  1197   3.0  978302268
6           1  1287   5.0  978302039
7           1  2804   5.0  978300719
8           1   594   4.0  978302268
9           1   919   4.0  978301368
10          1   595   5.0  978824268
11          1   938   4.0  978301752
12          1  2398   4.0  978302281
13          1  2918   4.0  978302124
14          1  1035   5.0  978301753
15          1  2791   4.0  978302188
16          1  2687   3.0  978824268
17          1  2018   4.0  978301777
18          1  3105   5.0  978301713
19          1  2797   4.0  978302039
20          1  2321   3.0  978302205
21          1   720   3.0  978300760
22          1  1270   5.0  978300055
23          1   527   5.0  978824195
24          1  2340   3.0  978300103
25          1    48   5.0  978824351
26          1  1097   4.0  978301953
27          1  1721   4.0  978300055
28          1  1545   4.0  978824139
29          1   745   3.0  978824268
...       ...   ...   ...        ...
1000179  6040  2762   4.0  956704584
1000180  6040  1036   3.0  956715455
1000181  6040   508   4.0  956704972
1000182  6040  1041   4.0  957717678
1000183  6040  3735   4.0  960971654
1000184  6040  2791   4.0  956715569
1000185  6040  2794   1.0  956716438
1000186  6040   527   5.0  956704219
1000187  6040  2003   1.0  956716294
1000188  6040   535   4.0  964828734
1000189  6040  2010   5.0  957716795
1000190  6040  2011   4.0  956716113
1000191  6040  3751   4.0  964828782
1000192  6040  2019   5.0  956703977
1000193  6040   541   4.0  956715288
1000194  6040  1077   5.0  964828799
1000195  6040  1079   2.0  956715648
1000196  6040   549   4.0  956704746
1000197  6040  2020   3.0  956715288
1000198  6040  2021   3.0  956716374
1000199  6040  2022   5.0  956716207
1000200  6040  2028   5.0  956704519
1000201  6040  1080   4.0  957717322
1000202  6040  1089   4.0  956704996
1000203  6040  1090   3.0  956715518
1000204  6040  1091   1.0  956716541
1000205  6040  1094   5.0  956704887
1000206  6040   562   5.0  956704746
1000207  6040  1096   4.0  956715648
1000208  6040  1097   4.0  956715569

[1000209 rows x 4 columns]

In [7]:
user = list(set(df.uid))
item = list(set(df.iid))
user_i = list(map(int, user))
item_i = list(map(int, item))

In [8]:
max(item_i)

3952

## Basic CF algorithm

In [9]:
from surprise import KNNBasic
trainset = data.build_full_trainset()
sim_options = {'name' : 'cosine', 'user_based' : True}

In [10]:
algo = KNNBasic(k = 40, min_k = 1, simoptions = sim_options)
algo.fit(trainset)

Computing the msd similarity matrix...
Done computing similarity matrix.


In [11]:
pred_rating_basic = np.zeros((max(user_i) + 1, max(item_i) + 1))
for u in user:
    iids = df[df.uid == u]
    for i in range(1, len(iids) + 1):
        iid = iids[i - 1:i].iid.values[0]
        r_ui = iids[i - 1:i].rate.values[0]
        pred = algo.predict(u, iid, r_ui, verbose = False)
        pred_rating_basic[int(u)][int(iid)] = pred.est

In [12]:
pred_rating_basic

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.85606058, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.62587977, 0.        , ..., 0.        , 0.        ,
        0.        ]])

## CF algorithm with mean

In [13]:
from surprise import KNNWithMeans

In [14]:
algo = KNNWithMeans(k = 40, min_k = 1, simoptions = sim_options)
algo.fit(trainset)

Computing the msd similarity matrix...
Done computing similarity matrix.


In [15]:
pred_rating_mean = np.zeros((max(user_i) + 1, max(item_i) + 1))
for u in user:
    iids = df[df.uid == u]
    for i in range(1, len(iids) + 1):
        iid = iids[i - 1:i].iid.values[0]
        r_ui = iids[i - 1:i].rate.values[0]
        pred = algo.predict(u, iid, r_ui, verbose = False)
        pred_rating_mean[int(u)][int(iid)] = pred.est

In [16]:
pred_rating_mean

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 5.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 3.4776764, 0.       , ..., 0.       , 0.       ,
        0.       ]])

## CF algorithm with z-score

In [17]:
from surprise import KNNWithZScore

In [18]:
algo = KNNWithZScore(k = 40, min_k = 1, simoptions = sim_options)
algo.fit(trainset)

Computing the msd similarity matrix...
Done computing similarity matrix.


In [19]:
pred_rating_z = np.zeros((max(user_i) + 1, max(item_i) + 1))
for u in user:
    iids = df[df.uid == u]
    for i in range(1, len(iids) + 1):
        iid = iids[i - 1:i].iid.values[0]
        r_ui = iids[i - 1:i].rate.values[0]
        pred = algo.predict(u, iid, r_ui, verbose = False)
        pred_rating_z[int(u)][int(iid)] = pred.est

In [20]:
pred_rating_z

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.81213531, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.45778811, 0.        , ..., 0.        , 0.        ,
        0.        ]])

## SVD

In [21]:
from surprise import SVD

In [22]:
algo = SVD(n_factors = 100, n_epochs = 20, biased = False, lr_all = 0.005, reg_all = 0)
algo.fit(trainset)

In [23]:
pred_rating_svd = np.zeros((max(user_i) + 1, max(item_i) + 1))
for u in user:
    iids = df[df.uid == u]
    for i in range(1, len(iids) + 1):
        iid = iids[i - 1:i].iid.values[0]
        r_ui = iids[i - 1:i].rate.values[0]
        pred = algo.predict(u, iid, r_ui, verbose = False)
        pred_rating_svd[int(u)][int(iid)] = pred.est

In [24]:
pred_rating_svd

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.72075285, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.05541747, 0.        , ..., 0.        , 0.        ,
        0.        ]])

## PMF

In [25]:
from surprise import SVD

In [26]:
algo = SVD(n_factors = 100, n_epochs = 20, biased = False, lr_all = 0.005, reg_all = 0.02)
algo.fit(trainset)

In [27]:
pred_rating_pmf = np.zeros((max(user_i) + 1, max(item_i) + 1))
for u in user:
    iids = df[df.uid == u]
    for i in range(1, len(iids) + 1):
        iid = iids[i - 1:i].iid.values[0]
        r_ui = iids[i - 1:i].rate.values[0]
        pred = algo.predict(u, iid, r_ui, verbose = False)
        pred_rating_pmf[int(u)][int(iid)] = pred.est

In [28]:
pred_rating_pmf

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.72957881, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.42034845, 0.        , ..., 0.        , 0.        ,
        0.        ]])

## PMF with biased

In [29]:
from surprise import SVD

In [30]:
algo = SVD(n_factors = 100, n_epochs = 20, biased = True, lr_all = 0.005, reg_all = 0.02)
algo.fit(trainset)

In [31]:
pred_rating_pmf_bi = np.zeros((max(user_i) + 1, max(item_i) + 1))
for u in user:
    iids = df[df.uid == u]
    for i in range(1, len(iids) + 1):
        iid = iids[i - 1:i].iid.values[0]
        r_ui = iids[i - 1:i].rate.values[0]
        pred = algo.predict(u, iid, r_ui, verbose = False)
        pred_rating_pmf_bi[int(u)][int(iid)] = pred.est

In [32]:
pred_rating_pmf_bi

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.49035194, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.64984629, 0.        , ..., 0.        , 0.        ,
        0.        ]])